### ISSUE TITLE
How to remove package?

### ISSUE THREAD

**Issue by artur9010** [oneye/oneye#36]
Hi,
how i can uninstall/remove package?

**Comment by lars-sh** [comment]
eyePackages cannot be removed in an automated way until now. eyePackages are simple archives, which are extracted to each installation's root directory and for now there is no mechanism to track those changes.

Even though, you could extract the specific eyePackage and remove containing files and folders from your installation by hand.

**Comment by artur9010** [comment]
Thanks for fast respond.
