### ISSUE TITLE
No taskbar when logging in as root

### ISSUE THREAD

**Issue by alexmocanu** [oneye/oneye#38]
When I login as root only the icons appear and nothing else. Logging in as another user doesn't show this issue. 

In Chrome's  dev. tools i get this error:

index.php?extern=apps/eyeX/js/eyeX.js:814 
POST http://localhost/oneye/index.php?checknum=925064257092&msg=baseapp 500 (Internal Server Error)

**Comment by lars-sh** [comment]
OK, let's see why this happens...

What version/revision of oneye are you using and what server (Apache, IIS, ...) and PHP version are you using?

PS: Please login with any user and call "Launch Application" from the system menu. Can you execute "eyeControl" when "Run as a different user" is "root"?
If yes, please create a new administrator user and check if you can login with that user.
