### ISSUE TITLE
Root password 

### ISSUE THREAD

**Issue by berserk82** [oneye/oneye#39]
Hello there. I tried installing oneye with the installer, but it doesn't remember the password I set.
Then I tried the oneye repository, but it doesn't allow me to create a new user and I don't know the root password. 
Please either tell me the root password or explain which changes do I need to make in order to enable new user creation.

Thanks in advance for either. 

Bye, Ivano.

**Comment by HawkWolf** [comment]
root/root

**Comment by berserk82** [comment]
Thanks a lot
