### ISSUE TITLE
Navigator

### ISSUE THREAD

**Issue by nikigre** [oneye/oneye#48]
Hi!
I have problems with Navigator. I tried in Chrome, Firefox, IE, Edge and I can't open almost any site.  The only page I have found that works are: http://oneye-project.org/. I read it on a forum here: http://forums.oneye-project.org/viewtopic.php?id=630 But I can't get it to work. I am using: oneye 0.9.0 (1.11.0.1).
Thank you

**Comment by lars-sh** [comment]
Hi.
Things changed a bit over time and for valid security reasons browser vendors invented further policies, which make using the Navigator more and more useless.
As an example, take a look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options .
