### ISSUE TITLE
sqlite not working...

### ISSUE THREAD

**Issue by PriNet** [oneye/oneye#50]
Environment:
Window 7 Pro
(testing on a 32 bit laptop before installing on main 64 bit machine)
Latest Win 7 Updates
Xampp (xampp-win32-1.7.7-VC9-installer) w/
MySQL, PHP, and Perl
oneye_0.9.0

Problem:
For the life of me, after several days of searching the internet, I
cannot find any viable solution to enabling 'php_sqlite.dll'. I have
tried enabling several times and cannot get it to show 'working'
during the install process. It shows up in the phpinfo() report, but
(as mentioned) I cannot get the 'email' to work. Everything else
appears to be functioning properly, including the ftp function
(which is the only way I can figure out how to get files from my
network into oneye, is there a way to 'link' to a network drive for
root to get files off my network?) Oh, I even tried loading that
'php_pdo.dll'  file that I found info about 'somewhere' on the net,
which btw failed (something about 64 bit?). Please (I don't expect
a response soon because there is no more development) can
someone explain to me how to get 'everything' working so I can
use the email feature? Maybe I'm just configuring something
wrong in oneye or it won't work properly on a 32 bit test machine?

phpinfo():
SQLite support | enabled
-- | --
PECL Module version | 2.0-dev $Id: sqlite.c 306939 2011-01-01 02:19:59Z felipe $
SQLite Library | 2.8.17
SQLite Encoding | iso8859
 (I assumed this meant it was working)

-G

P.S. I love the software btw...

**Comment by lars-sh** [comment]
Don't hesitate, things should be fine for you. It's just the installer, that's doing bad stuff. https://github.com/oneye/installer/commit/9b2e4dc50788d6dcbde091fae78bebc4ae28daef should fix that.
