### ISSUE TITLE
Default repo empty

### ISSUE THREAD

**Issue by szalony9szymek** [oneye/oneye#53]
I connect and update without issues, but eyeSoft is still empty

**Comment by szalony9szymek** [comment]
i also had to add the same as defult repo, but with https for it to connect

**Comment by szalony9szymek** [comment]
but it is stll empty

**Comment by lars-sh** [comment]
Please try again now. I just configured forwarding http://soft.oneye-project.org/ to https://soft.oneye-project.org/ - sadly that broke the oneye packages manager.

In case you still do not see the applications, please add a new repository with the URL http://soft.oneye-project.org/? to avoid redirection caches to take effect.

**Comment by szalony9szymek** [comment]
where is the repo config file stored, I cannot add it via the system preferences?

**Comment by lars-sh** [comment]
Please make sure to configure the root user by selecting the correct user inside the system preferences or login as root user.

The below screenshot should show the rest. Just ask in case that did not help.

![image](https://user-images.githubusercontent.com/880198/91667908-42ba6900-eb08-11ea-8770-fe50cb835473.png)

**Comment by szalony9szymek** [comment]
I am logged in as root, I just wanna add it manually via file explorer on the computer with the php server, is it possible?

**Comment by lars-sh** [comment]
Just add an additional `mirror` tag to `system_xxxxxxxx/system/conf/ports.xml`.

**Comment by szalony9szymek** [comment]
thx
