### ISSUE TITLE
A submodule points to a commit which does not exist.

### ISSUE THREAD

**Issue by namnhatpham1995** [oneye/oneye#55]
When I try to clone this project to my computer, I receive this message "A submodule points to a commit which does not exist.".
Can you check what happen?

**Comment by lars-sh** [comment]
Hmm... With the classic Git client submodules are not resolved unless you explicitly ask for it. Please check if the repository has been cloned even when receiving that message.

The file https://github.com/oneye/oneye/blob/master/.gitmodules contains all submodules. I just checked out all those four repositories and they all exist. But it seems, the unoconv entry is missing the ending `.git`. Might that be a problem? Please try it out.

**Comment by lars-sh** [comment]
Well, I just tried out updating the submodules myself and it seems, the UglifyJS submodule commit has been removed from their repository. Please try again with the latest commit.
