### ISSUE TITLE
Make it mobile

### ISSUE THREAD

**Issue by anonimo82** [oneye/oneye#57]
This could be so cool, if only it were mobile friendly.
It's possible, and it needs few modification. 

App's windows should take all available space (force Apps to full-screen), making the menu, the left and right sidebar and the main (content) area scrollable, all of them with 2 finger gestures (a swipe with one finger should be detected as a click+drag), main menus (the Apps launcher menu) should follow the same rule.

I know it's almost as this already, but there are random incongruencies in the UI - these should be fixed.

If you hard code these in the "general" user interface, instead of "per App", Apps UI should act accordingly. Obviously, this only goes for mobile browsers, so browser or OS sniffing is required.

Thanks so much for reading, I sincerely hope you'll consider this.

Bye, Ivano.

**Comment by chiaravalle** [comment]
Yes, this would be sooooooo cool!

**Comment by anonimo82** [comment]
@lars-sh any feedback?

**Comment by lars-sh** [comment]
@anonimo82, I discontinued oneye quite a while ago. There already is a mobile-friendly version, which can be accessed using `URL/mobile` and there's an iPhone version accessible via `URL/iphone`.
*But* those two give access to the files only and they're... really old.

Even though, at least application windows should be maximized as the browser window gets smaller. Did you notice that already?

**Comment by anonimo82** [comment]
Yes, I saw the Android version, and it disappointed me.
What do you mean with "smaller window"?
