### ISSUE TITLE
Introduce the "store" concept

### ISSUE THREAD

**Issue by anonimo82** [oneye/oneye#58]
Something like Apple App Store, Microsoft Store, Play Store, etc.
Allow each user to [un]install Apps he wants, and not use a single source for Apps.
In example, enable different users to have different Apps in their account.

I know this will be a big effort, but many could benefit.

**Comment by chiaravalle** [comment]
Oh, so you're going to make OnLine Android???

**Comment by anonimo82** [comment]
No, just make the user able to choose which Apps to get in his account.
@lars-sh any feedback?

**Comment by lars-sh** [comment]
@anonimo82, that's already possible. You can simply setup your oft eyeSoft repository and configure it in the System Preferences. Just have a look at https://github.com/oneye/soft , which is what http://soft.oneye-project.org/ is based on.

**Comment by anonimo82** [comment]
Great, thanks.
I guess we can close this?
